server:
  port: 8857
spring:
  application:
    name: A34BackEnd
  datasource:
    url: jdbc:mysql://1.15.242.140/:3306/rfid?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: a34_test
    password: 5deT4zT5hKpfFYhj
    driver-class-name: com.mysql.cj.jdbc.Driver


  elasticsearch:
    uris: http://127.0.0.1:9200
    host: 127.0.0.1:9200
    username: elastic
    password: kiminouso030221


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

settings:
  debug-level: 1
  worker-id: 1
  datacenter-id: 1
  PDFData:
    expireTimeoutMinutes: 1
  auth-server:
    url: http://1.15.242.140:8855/verification/verifyToken
    auth-key: AGLQwrl9gzazdAgv
redis:
  host: 127.0.0.1
  port: 6379
  password: admin12345
  database:
    for-doc-feedback: 1
    for-pdf-cache: 4
  doc-feedback:
    key-prefix:
      preference: p
      extraction-count: e
      visit-count: v
    key-prefix-separator: _ #键的前缀和键之间的分隔符
minio:
  endpoint: http://96.9.225.169:9000
  access-key: bdDe76sWOlb22rm4
  secret-key: rzkgQC26aOL5ljIrBIaOWNPTDQA54LAe
  buckets: pdf, pdf2



