server:
  port: 8887
spring:
  application:
    name: A34BackEnd
  datasource:
    url: jdbc:mysql://1.15.242.140:3306/a34_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: a34_test
    password: 5deT4zT5hKpfFYhj
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: kiminouso030221
  data:
    redis:
      host: 127.0.0.1
      port: 6379


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

setting:
  debug-level: 1
  work-id: 1
  datacenter-id: 1
  pdf-file-path: 'F:/static/pdf'
  pdf-temp-path: 'F:/static/temp'
  auth-server:
    address: "http://127.0.0.1:8857"
    auth-key: "AGLQwrl9gzazdAgv"

test:
  test-pdf: "/root/a34/pdf/test.pdf"