server:
  port: 8857
spring:
  application:
    name: A34BackEnd
  datasource:
    url: jdbc:mysql://1.15.242.140/:3306/rfid?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: a34_test
    password: 5deT4zT5hKpfFYhj
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    # 池中最小空闲连接数量，默认值10
    minimum-idle: 5
    # 空闲时间
    idle-timeout: 600000
    # 池中最大连接数（包括空闲和正在使用的连接）
    maximum-pool-size: 10
    # 是否自动提交池中返回的连接
    auto-commit: true
    # 连接池的名字
    pool-name: MyHikariCP
    # 连接池中连接的最大生命周期
    max-lifetime: 1800000
    # 连接超时时间。默认值为30s
    connection-timeout: 30000


  elasticsearch:
    uris: http://127.0.0.1:9200
    host: 127.0.0.1:9200
    username: elastic
    password: kiminouso030221


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

settings:
  debug-level: 1
  worker-id: 1
  datacenter-id: 1
  PDFData:
    expireTimeoutMinutes: 1
  auth-server:
    url: http://127.0.0.1:8855/verification/verifyToken
    auth-key: AGLQwrl9gzazdAgv
redis:
  host: 127.0.0.1
  port: 6379
  password: admin12345
  database:
    for-doc-feedback: 1
    for-pdf-cache: 4
  doc-feedback:
    key-prefix:
      preference: p
      extraction-count: e
      visit-count: v
    key-prefix-separator: _ #键的前缀和键之间的分隔符
minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: admin12345
  buckets: pdf, pdf2



